// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpgrjyysxeboeaksousa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZ3JqeXlzeGVib2Vha3NvdXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2OTIxMzAsImV4cCI6MjA3NTI2ODEzMH0.dObkaVito9FrgiBFHMbGNF7AkNrlggsQqr-M4_63dxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});