// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbcgwtnewwknjzsbielm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiY2d3dG5ld3drbmp6c2JpZWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODQyNTUsImV4cCI6MjA3NDE2MDI1NX0.nXRoIpS9mDm3uo-q93h4HCsQTh_M1JV3OqdA5P5aGbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});